name: CI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Katalon Studio Github Action
      uses: katalon-studio/katalon-studio-github-action@v2
      with:
          version: '7.5.5'
          projectPath: '${{ github.workspace }}'
          args: '-noSplash -retry=0 -browserType=Chrome -statusDelay=15 -testSuitePath="Test Suites/DemoTestSuite" -apiKey= ${{ secrets.API_KEY }} --config -webui.autoUpdateDrivers=true'
  report:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Katalon Report Uploader
      uses: katalon-studio/report-uploader@v0.0.8
      env:
          PASSWORD: fd1aaab3-1ce1-415a-ad04-ccd98182a331
          PROJECT_ID: 168078
          TYPE: katalon
          REPORT_PATH: 'D:\a\Academy_Automation_Test\Academy_Automation_Test\Reports'

